

drop table books;
create table BOOKS(
     id bigint generated by default as identity default on null
    , TITLE VARCHAR(50) NOT NULL
    , AUTHORFNAME VARCHAR(50)
    , AUTHORLNAME VARCHAR(50)
    ,  PRICE INT
    ,  GENRE VARCHAR(50)
    , DETAILEDDESCRIPTION VARCHAR(50)
    , NOTES VARCHAR(50)
    , STATUS VARCHAR(50)
    , VERSION INT
    , CREATED_AT TIMESTAMP NOT NULL
    , MODIFIED_AT TIMESTAMP NOT NULL
    , UNIQUE(TITLE)
);
drop table PERSON;

CREATE TABLE PERSON
(
    id bigint generated by default as identity default on null
    , USERNAME VARCHAR(50) NOT NULL
    , FIRSTNAME VARCHAR(50)
    , LASTNAME VARCHAR(50)
    , PASSWORD VARCHAR(50) NOT NULL
    , REGISTERDATE TIMESTAMP
    , VERSION INT
    , CREATED_AT TIMESTAMP NOT NULL
    , MODIFIED_AT TIMESTAMP NOT NULL
    , UNIQUE(USERNAME)
);

CREATE TABLE AUTHOR
(
    id bigint generated by default as identity default on null
    ,  FIRSTNAME VARCHAR(50)
    , LASTNAME VARCHAR(50)
    , BIRTHDATE DATETIME
    , REGISTERDATE TIMESTAMP
    , VERSION INT
    , CREATED_AT TIMESTAMP NOT NULL
    , MODIFIED_AT TIMESTAMP NOT NULL
    , UNIQUE(LASTNAME)
);

CREATE TABLE  USERS
(
    id bigint generated by default as identity default on null
    , USERNAME VARCHAR(50) NOT NULL
    , FIRSTNAME VARCHAR(50)
    , LASTNAME VARCHAR(50)
    , PASSWORD VARCHAR(50) NOT NULL
    , SALT VARCHAR(50)
    , REGISTERDATE TIMESTAMP
    , VERSION INT
    , CREATED_AT TIMESTAMP NOT NULL
    , MODIFIED_AT TIMESTAMP NOT NULL
    , UNIQUE(USERNAME)
);



create table person_list(
     person_id bigint
    ,book_id bigint
);
create table author_list(
    author_id bigint,
    book_id bigint
);
create table user_list(
    user_id bigint,
    book_id bigint
);

INSERT INTO PERSON(ID, USERNAME, FIRSTNAME, LASTNAME, PASSWORD, REGISTERDATE, VERSION, CREATED_AT, MODIFIED_AT) VALUES (1, 'sherlock.holmes', 'Sherlock', 'Holmes', '123ss12sh', '1983-08-18 00:01', 1, '1983-08-18 00:01', '1999-03-18 00:02' );
